
USE alexsnchzleiva;

DROP TABLE PRUEBA;

CREATE TABLE IF NOT EXISTS PRUEBA
(
	NOMBRE VARCHAR(30),
	CONSTRAINT PK_PRUEBA PRIMARY KEY (NOMBRE)
);

INSERT INTO PRUEBA VALUES("ALEJANDRO");

SELECT * FROM PRUEBA;